name: pinball-const-set # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: DOS version of Pinball Construction Set
description: |
  DOS version of Pinball Construction Set

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  pinball-const-set_icon.png
title: Pinball Construction Set (DOS)

apps:
  pinball-const-set:
    command: dosbox -exit PCS.EXE
parts:
  pinball-const-set:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
    build-packages: [dosbox]
    stage-packages: [dosbox]
    organize:
      pinball-const-set: build/
      pinball-const-set.1: man/man1/

architectures:
  - build-on: amd64

